lxc/terraform-provider-incus

docs/resources/storage_bucket.md
docs/resources/storage_bucket_key.md
internal/provider/provider.go
internal/storage/resource_storage_bucket.go
internal/storage/resource_storage_bucket_key.go
internal/storage/resource_storage_bucket_key_test.go
internal/storage/resource_storage_bucket_test.go

This pull request aims to improve the capabilities of this Terraform provider by adding support for managing storage buckets and their access keys.
**Storage Bucket Creation**
```hcl
resource "incus_storage_bucket" "bucket1" {
name    = "bucket1"
project = "default"
pool    = "default"
}
resource "incus_storage_bucket_key" "reader" {
name           = "reader"
description    = "Read-Only User"
pool           = incus_storage_bucket.bucket1.pool
storage_bucket = incus_storage_bucket.bucket1.name
}
resource "incus_storage_bucket_key" "writer" {
name           = "writer"
description    = "Write User"
role           = "admin"
pool           = incus_storage_bucket.bucket1.pool
storage_bucket = incus_storage_bucket.test1.name
}
```
**Import existing Storage Bucket and Key**
```hcl
resource …
```

Introduce Storage Bucket Resource

---

internal/project/resource_project.go
internal/project/resource_project_test.go

This pull request adds the ability to import projects, such as with `tofu import incus_project.project1 project1`. I added tests as well using the tests used for networks as a reference.
My Go is rusty so let me know if I should improve this PR in any way!

Add ability to import projects

---

internal/provider/provider.go

Expand ConfigDir env vars when config.yml is missing

---

internal/instance/resource_instance.go

With virtual machines that don't run our agent, Processes will remain 0 forever. As the check is really meant to make sure that the instance has started, checking for the PID should be more reliable.

resource/instance: Check PID not processes

---

internal/storage/resource_storage_bucket.go

This pull request fixes the situation where `incus_storage_bucket` produces an inconsistent result when using the `lvm` storage driver, see https://github.com/lxc/terraform-provider-incus/issues/47.
The same solution is already used in other resources, e.g:
* https://github.com/lxc/terraform-provider-incus/blob/main/internal/storage/resource_storage_volume.go#L380-L385
* https://github.com/lxc/terraform-provider-incus/blob/main/internal/storage/resource_storage_pool.go#L337-L372

FIX: incus_storage_bucket produces inconsistent result 

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

This pull request addresses https://github.com/lxc/terraform-provider-incus/issues/26 by adding CODE_OF_CONDUCT.md and CONTRIBUTING.md, establishing behavior standards and contribution guidelines for project participants similar to the [Incus Contributions Guideline](https://github.com/lxc/incus/blob/main/CONTRIBUTING.md).

Add contributions guideline

---

docs/data-sources/profile.md
internal/profile/datasource_profile.go
internal/provider/provider.go

This pull request introduces a new data source for Incus profiles in the Terraform provider for Incus. 
This makes it possible to use an existing profile that was not created by Terraform, such as the default profile as mentioned in https://github.com/lxc/terraform-provider-incus/issues/58:
```hcl
data "incus_profile" "default" {
name = "default"
}
resource "incus_instance" "d1" {
profiles = [data.incus_profile.default.name]
image    = "images:debian/12"
name     = "d1"
}
```
Documentation:
* [`docs/data-sources/profile.md`](diffhunk://#diff-f89b844c330b464001c606af33eb2d17a51f35e6ac2ddfdd7ff962f1282d91f0R1-R43): Added documentation for the new `incus_profile` data source, including example usage, argument reference, and attribute reference.
Changes:
* …

Add Profile as data source

---

internal/provider-config/config.go

This pull request contains a change to the function `determineIncusDir` in the file `internal/provider-config/config.go`. The function has been revised to iterate directly over potential socket paths instead of directory paths. This should fix https://github.com/lxc/terraform-provider-incus/issues/61.

Take `unix.socket`and `unix.socket.user` into account to determine INCUS_DIR

---

internal/common/incus_config.go
internal/instance/resource_instance.go
internal/network/resource_network.go
internal/network/resource_network_lb.go
internal/network/resource_network_test.go
internal/network/resource_network_zone.go
internal/network/resource_network_zone_record.go
internal/profile/datasource_profile.go
internal/profile/resource_profile.go
internal/project/resource_project.go
internal/storage/resource_storage_bucket.go
internal/storage/resource_storage_pool.go
internal/storage/resource_storage_volume.go

Terraform allows for configuration to be set to NULL. This is generally assumed to be equivalent to not having put the configuration line in question and is particularly useful when dealing with conditional behaviors.
A couple of examples:
```
resource "incus_network" "this" {
name = "foo"
config = {
"ipv4.address" = var.deploy == "production" ? "none" : null
}
}
resource "incus_profile" "this" {
name = "foo"
config = {
"environment.http_proxy" = var.deploy == "production" ? "http://my-proxy:3128" : null
"environment.https_proxy" = var.deploy == "production" ? "http://my-proxy:3128" : null
}
}
```
To handle this properly, a few changes are needed:
- Read the Terraform config as a map[string]*string to allow for NULL
- When set to NULL and config key doesn't exist, tell Terraform it's NULL …

Support NULL values in configs

---

internal/storage/resource_storage_volume.go
internal/storage/resource_storage_volume_test.go

This pull request fixes https://github.com/lxc/terraform-provider-incus/issues/43:
In the event that a storage pool has a configuration value set for `volume.*`, the Terraform provider takes into account that this key is inherited (computed) to the storage volume after creation:
**Steps to reproduce:**
```hcl
resource "incus_storage_pool" "test" {
name    = "test"
project = "default"
driver  = "zfs"
config = {
"volume.zfs.remove_snapshots" = "true"
}
}
resource "incus_storage_volume" "test" {
name         = "test"
pool         = incus_storage_pool.test.name
content_type = "block"
config = {
"size" = "1GiB"
}
}
```
```bash
$ terraform apply
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
+ create …
```

storage: Combine the inherited storage pool volume keys with the computed keys for storage pool volume

---

docs/resources/network_acl.md
internal/network/resource_network_acl.go
internal/network/resource_network_acl_test.go
internal/provider/provider.go

This pull requests adds the network ACL resource (see https://github.com/lxc/terraform-provider-incus/issues/78).
**Examples**
```hcl
resource "incus_network_acl" "this" {
name        = "my-acl"
description = "foo"
}
```
```hcl
resource "incus_network_acl" "this" {
name        = "my-acl"
description = "foo"
egress = [
{
action           = "allow"
destination      = "1.1.1.1,1.0.0.1"
destination_port = "53"
protocol         = "udp"
description      = "DNS to cloudflare public resolvers (UDP)"
state            = "enabled"
},
{
action           = "allow"
destination      = "1.1.1.1,1.0.0.1"
destination_port = "53"
protocol         = "tcp"
description      = "DNS to cloudflare public resolvers (TCP)"
state            = "enabled"
}
]
ingress = [
{
action           = "allow"
source           = …
```

Add network ACL resource

---

docs/resources/network_forward.md
internal/network/resource_network_forward.go
internal/network/resource_network_forward_test.go
internal/provider/provider.go

This pull requests adds the network forward resource (see https://github.com/lxc/terraform-provider-incus/issues/35).
**Examples**
```hcl
resource "incus_network" "my_network" {
name = "my-network"
config = {
"ipv4.address" = "10.150.19.1/24"
"ipv4.nat"     = "true"
"ipv6.address" = "fd42:474b:622d:259d::1/64"
"ipv6.nat"     = "true"
}
}
resource "incus_network_forward" "my_forward" {
network        = incus_network.my_network.name
listen_address = "10.150.19.10"
config = {
target_address = "10.150.19.111"
}
ports = [
{
description    = "SSH"
protocol       = "tcp"
listen_port    = "22"
target_port    = "2022"
target_address = "10.150.19.112"
},
{
description    = "HTTP"
protocol       = "tcp"
listen_port    = "80"
target_port    = "8080"
target_address = "10.150.19.112"
}
]
}
```
**What's …

Add network forward resource

---

internal/instance/resource_instance.go
internal/instance/resource_instance_test.go

This pull request allow the creation of [empty instance](https://linuxcontainers.org/incus/docs/main/howto/instances_create/#launch-a-vm-that-boots-from-an-iso) with no image.
It fixes #42 and introduce a new ACC test (`TestAccInstance_noImage`).

Instance: Make `image` attribut optional

---

internal/image/resource_image_test.go
internal/instance/resource_instance.go

If Image Remote is not set, the instance server is used as the image server.
This pull request fixes: https://github.com/lxc/terraform-provider-incus/issues/94
**Example:**
```tf
resource "incus_project" "test" {
name = "test"
config = {
"features.images"   = true
"features.profiles" = false
}
}
resource "incus_image" "alpine" {
source_remote = "images"
source_image  = "alpine/3.18/arm64"
project       = incus_project.test.name
}
resource "incus_instance" "test1" {
name    = "test1"
image   = "images:alpine/3.18/arm64"
project = incus_project.test.name
}
resource "incus_instance" "test2" {
name    = "test2"
image   = incus_image.alpine.fingerprint
project = incus_project.test.name
}
```

Fix: If Image Remote is not set, the instance server is used as the image server.

---

docs/resources/image.md
internal/image/resource_image.go
internal/image/resource_image_test.go
internal/image/schema_validators.go

This pull request fixes https://github.com/lxc/terraform-provider-incus/issues/92 by making `Architecture` an argument.
**Example**
```hcl
resource "incus_project" "test" {
name = "test"
}
resource "incus_image" "ubuntu" {
project = incus_project.test.name
source_remote = "images"
source_image  = "ubuntu/noble"
architecture  = "aarch64"
}
```
**What's been done**
- Changed `incus_image` to make Architecture an argument and use `IncusClient#GetImageAliasArchitectures` to determine the correct image alias
- Added test to validate the argument
- Updated documentation

Architecture becomes argument

---

internal/network/resource_network_lb.go
internal/network/resource_network_lb_test.go

This pull request fixes https://github.com/lxc/terraform-provider-incus/issues/101
**Whats been done**
- Allow backend description to be null by setting an empty default value
- Added test

Allow LB backend description to be null

---

.github/workflows/test.yml
internal/instance/resource_instance.go
internal/instance/resource_instance_test.go
internal/provider-config/config.go

This pull requests adds an initial support to create a OCI container with this provider.
**Example**
```hcl
resource "incus_instance" "redis" {
project = "default"
name    = "redis"
image   = "docker:redis"
}
```
**What's been done** 
- Added support for OCI protocol
- Added `environment.` to the computed keys list in `resource_instance.go`
- Added test to run an OCI image
- Added DockerHub as remote for test environment

instance: Add OCI container support

---

docs/resources/instance.md
internal/instance/resource_instance.go
internal/instance/resource_instance_test.go

This pull requests adds the `source_instance` argument to use another instance as the source for a new instance, see https://github.com/lxc/terraform-provider-incus/issues/80
**Examples**
_From current instance:_
```hcl
resource "incus_instance" "instance1" {
project = "default"
name    = "instance1"
image   = "images:debian/12"
}
resource "incus_instance" "instance2" {
project = "default"
name    = "instance1"
source_instance = {
project = "default"
name    = incus_instance.instance1.name
}
}
```
_From a snapshot of the source instance:_
```hcl
resource "incus_instance" "instance1" {
project = "default"
name    = "instance1"
image   = "images:debian/12"
}
resource "incus_instance_snapshot" "snapshot1" {
project  = "default"
name     = "snap0"
instance = incus_instance.instance1.name
} …
```

Use another instance as the source for a new instance

---

docs/resources/instance.md

The old link returns a 404. Looking at the git history, it looks like the file was renamed in https://github.com/lxc/incus/commit/9d18f53a9ad3990082af65b1b74a722082989525.

Fix Image Server Link

---

docs/data-sources/image.md
internal/image/datasource_image.go
internal/provider/provider.go

This pull requests adds the image datasource as discussed in https://github.com/lxc/terraform-provider-incus/issues/96.
**Example**
```hcl
data "incus_image" "my_image" {
name = "my_image" # is the alias of the image, fingerprint would also be possible to set instead
}
output "fingerprint" {
value = data.incus_image.my_image.fingerprint
}
resource "incus_instance" "instance1" {
image = data.incus_image.my_image.fingerprint
name  = "instance1"
}
```
**What's been done**
- Added image datasource
- Added docs for image datasource

image: Add image datasource

---

docs/resources/instance.md
internal/instance/resource_instance.go
internal/instance/resource_instance_test.go
internal/instance/schema_validators.go

This pull request fixes https://github.com/lxc/terraform-provider-incus/issues/134

Remove limits

---

internal/instance/resource_instance.go
internal/provider-config/config.go

This pull requests fixes https://github.com/lxc/terraform-provider-incus/issues/119 as we support public image servers now.
**Example**
```hcl
resource "incus_instance" "a1" {
remote = "instance-server"
name   = "a1"
image  = "public-image-server:my-custom-alpine"
}
```

Support public image servers

---

docs/data-sources/profile.md
docs/data-sources/project.md
internal/project/datasource_project.go
internal/provider/provider.go

This pull requests adds the project datasource.
**Example**
```hcl
data "incus_project" "default" {
name = "default"
}
output "project_config" {
value = data.incus_project.default.config
}
resource "incus_instance" "d1" {
project = data.incus_project.default.name
image    = "images:debian/12"
name     = "d1"
}
```
**What's been done**
- Added project datasource
- Added docs for project datasource
- Improved profile documentation

Add project as datasource

---

docs/resources/cluster_group.md
docs/resources/cluster_group_assignment.md
internal/clustering/resource_cluster_group.go
internal/clustering/resource_cluster_group_assignment.go
internal/clustering/resource_cluster_group_assignment_test.go
internal/clustering/resource_cluster_group_test.go
internal/provider/provider.go

**Description**
This pull requests adds the cluster group and cluster group assignment resource and fixes https://github.com/lxc/terraform-provider-incus/issues/121.
I decided to make an assignment an explicit resource as I have seen done by other [providers](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_account_assignment).
_Example_:
```hcl
resource "incus_cluster_group" "amd64" {
name        = "amd64"
description = "x86 machines"
}
resource "incus_cluster_group_assignment" "incus_dev_1" {
cluster_group = incus_cluster_group.amd64.name
member        = "incus-dev-1"
}
```

Cluster group resource

---

docs/resources/certificate.md
internal/config/resource_certificate.go
internal/config/resource_certificate_test.go
internal/provider/provider.go

This pull requests adds the certificate resource as described here: https://github.com/lxc/terraform-provider-incus/issues/120.
**Example**
```hcl
resource "incus_project" "myproject" {
name = "myproject"
}
resource "incus_certificate" "metrics" {
name        = "prometheus"
description = "Prometheus Node Exporter Access"
restricted  = true
projects    = [incus_project.myproject.name]
type        = "metrics"
certificate = file("${path.module}/metrics.crt")
}
output "fingerprint" {
value = incus_certificate.metrics.fingerprint
}
```

Add certificate resource

---

docs/resources/storage_bucket.md
internal/storage/resource_storage_bucket.go

Close #127 
Add source_file to incus_storage_bucket
```
root@playground:~/terraform-incus# incus storage bucket create default mybucket
Storage bucket "mybucket" created
Admin access key: 20UYEVYRYC11LAX0L1UQ
Admin secret key: 6t7ETtVRR9getp3oIUOQuKFYWHRLR52JONe7cktX
root@playground:~/terraform-incus# incus storage bucket list default
+----------+-------------+
|   NAME   | DESCRIPTION |
+----------+-------------+
| mybucket |             |
+----------+-------------+
root@playground:~/terraform-incus# incus storage bucket export default mybucket
Backup exported successfully!
root@playground:~/terraform-incus# incus storage bucket delete default mybucket
Storage bucket "mybucket" deleted
root@playground:~/terraform-incus# incus storage bucket ls default
+------+-------------+
| NAME | …
```

Add source_file to incus_storage_bucket

---

internal/instance/resource_instance.go
internal/network/resource_network_test.go

This should fix the flake acceptance tests where ipv4 address is not set, e.g. https://github.com/lxc/terraform-provider-incus/actions/runs/11933941679/job/33262025197#step:8:242

bugfix: fix interface sort order

---

docs/resources/storage_volume.md
internal/storage/resource_storage_volume.go
internal/storage/resource_storage_volume_test.go

Close #126 
Add source_file to incus_storage_volume
**Export the backup volume**
```
root@playground:~/backup# incus storage volume list mypool
+--------+----------+-------------+--------------+---------+
|  TYPE  |   NAME   | DESCRIPTION | CONTENT-TYPE | USED BY |
+--------+----------+-------------+--------------+---------+
| custom | myvolume |             | filesystem   | 0       |
+--------+----------+-------------+--------------+---------+
root@playground:~/backup# incus storage volume export mypool myvolume
Backup exported successfully!
root@playground:~/backup# ls
backup.tar.gz
```
**Import the backup volume by terraform with source_file argument**
```
root@playground:~/terraform-incus# terraform apply
╷
│ Warning: Provider development overrides are in effect
│
│ The following …
```

Add source_file to incus_storage_volume

---

docs/resources/network_integration.md
internal/network/resource_network_integration.go
internal/network/resource_network_integration_test.go
internal/provider/provider.go

Closes https://github.com/lxc/terraform-provider-incus/issues/122

network_integration: add network_integration resource

---

docs/resources/image.md
internal/image/resource_image.go
internal/image/resource_image_test.go
internal/utils/utils.go

Add source_file to incus_image

---

docs/index.md

I was confused when trying to define the remote block for the incus host I want Terraform/OpenTofu to talk to and was using variables to set the values for the remote. While the arguments are optional and some of the defaults are stated I found that the `schema` value can change how the `address` argument is used. When the arguments are not present they will use a default value, but I needed the same behavior when an argument was present and contained a value.
I thought it might be useful to provide both an example of a defined local connection to a UNIX socket and a connection to a remote Incus host that would connect over HTTPS.
I also provided a suggestion for updating the description on the `address` field to indicate how the fields value changes when `schema` is set to `unix`.

Improve remote block docs for local unix sockets

---

.github/workflows/test.yml
docs/resources/network_integration.md
docs/resources/network_peer.md
internal/network/resource_network_integration_test.go
internal/network/resource_network_peer.go
internal/network/resource_network_peer_test.go
internal/provider/provider.go

Hello,
This is the PR for https://github.com/lxc/terraform-provider-incus/issues/123.

Add new incus_network_peer resource

---

internal/provider-config/config.go

This pull request fixes https://github.com/lxc/terraform-provider-incus/issues/200.
---
When running this provider, we set the `INCUS_DIR` environment variable at one point in the config: https://github.com/lxc/terraform-provider-incus/blob/0fbc28b57ffc6b0acbeae63408d646f9c78c2b7e/internal/provider-config/config.go#L165
To ensure that `unix.socket.user` is writable when `INCUS_DIR` is set, we must validate this too properly.

provider-config: Check if unix.socket.user is writable when INCUS_DIR is set

---

internal/network/resource_network.go

This pull request fixes: https://github.com/lxc/terraform-provider-incus/issues/202
---
When a new OVN network is created in a project with a restricted network uplink, then the Incus server sets the network property that we need to accept in the returned state.

network: Add network as computed key

---

internal/network/resource_network_lb.go
internal/network/resource_network_lb_test.go

This pull request fixes: https://github.com/lxc/terraform-provider-incus/issues/196
---
`backend.target_port` and `port.description` are computed string values that require proper default values to avoid inconsistent results after apply.

network: Set proper default values in network load-balancer

---

docs/resources/image.md

Change documentation to clarify that image.copy_aliases is not set to true by default. https://github.com/lxc/terraform-provider-incus/issues/209

docs: image copy_aliases is not set by default to true

---

internal/instance/resource_instance.go

The new validation checks that the instance is runnning when files should be pushed to the instance. Otherwise a validation error message is returned, fixes: https://github.com/lxc/terraform-provider-incus/issues/164

instance: Add valiation for pushing files

---

TESTING.md
docs/resources/instance.md
internal/acctest/provider_factory.go
internal/instance/resource_instance.go
internal/instance/resource_instance_test.go
internal/network/resource_network_test.go

This pull request introduces significant changes to the `incus_instance` resource, removing the `wait_for_network` attribute for the new `wait_for` syntax.
The new `wait_for` syntax supports the following types:
- `agent`: Waits for the Incus agent to be responding
- `delay`: Waits for a specific amount of time
- `ipv4`: Waits for the IPv4 network to be ready
- `ipv6`: Waits for an IPv6 network to be ready
- `ready`: Waits for the Incus instance to be ready (Instance State == `READY`)
**Breaking changes:**
- We used to wait for the IPv4 network to be ready by default, but that’s not the case anymore. To revert to this behavior, set the `wait_for` block with type `ipv4`.
- We now wait for an instance to be in the `RUNNING` state instead of also waiting for the Incus agent to be running …

New `wait_for` configuration block for instance resource

---

internal/instance/resource_instance.go

I added [declarative validator](https://github.com/hashicorp/terraform-plugin-framework-validators/tree/main/stringvalidator) built-in the provider framework instead of imperatively checking in Validate function.

Add plugin framework conflics_with and at_least_one_of to instance

---

internal/common/incus_config.go
internal/network/resource_network.go

This pull request introduces a new validation method to the `incus_network` resource  to ensures that `ipv4.address` and `ipv6.address` cannot be set to `auto`, fixes: https://github.com/lxc/terraform-provider-incus/issues/57

network: Disallow auto for ipv4.address and ipv6.address

---

internal/provider-config/config.go

Tested using Fedora, should also work on OpenSUSE and Arch.

 Fix running acceptance tests on different distributions when using the socket

---

docs/resources/instance.md
internal/acctest/checks.go
internal/common/schema_validators.go
internal/image/datasource_image.go
internal/image/resource_image.go
internal/instance/resource_instance.go
internal/instance/resource_instance_test.go

This pull request adds support for specifying an architecture when creating an empty instance (fixes: #218). It also ensures that the architecture is set and accessible for instances created from images, source files, or other instances.
**Example:**
```hcl
resource "incus_instance" "a1" {
name         = "a1"
architecture = "x86_64"
running      = false
}
```
The architecture attribute is now available for use in output variables too:
```hcl
resource "incus_instance" "a1" {
name         = "a1"
architecture = "x86_64"
running      = false
}
resource "incus_instance" "a2" {
name    = "a2"
image   = "images:alpine/edge"
running = false
}
output "a1_arch" {
value = incus_instance.a1.architecture
}
output "a2_arch" {
value = incus_instance.a2.architecture
}
```

Instance architecture

---

.gitignore

Just like IntellJ-based IDEs, we also ignore all VSCode configurations that are saved in the `.vscode` directory.

gitignore: Ignore VSCode configurations

---

internal/network/resource_network_acl.go

This pull request addresses the issue where the name of an `incus_network_acl` resource is modified which currently leads to the following issue:
```hcl
$ tofu apply
incus_network_acl.this: Refreshing state... [name=my-acl]
OpenTofu used the selected providers to generate the following execution plan.
Resource actions are indicated with the following symbols:
~ update in-place
OpenTofu will perform the following actions:
~ resource "incus_network_acl" "this" {
~ name        = "my-acl" -> "my-acld"
}
Plan: 0 to add, 1 to change, 0 to destroy.
Do you want to perform these actions?
OpenTofu will perform the actions described above.
Only 'yes' will be accepted to approve.
Enter a value: yes
incus_network_acl.this: Modifying... [name=my-acl]
╷
│ Error: Failed to retrieve existing network ACL …
```

network: Force network ACL recreation when name was changed

---

docs/resources/image.md
internal/image/resource_image.go
internal/image/resource_image_test.go

This pull request implements the `incus_image_alias` resource.
close #221 
**Terraform Configuration**
```
resource "incus_image" "img" {
source_image = {
remote = "images"
name   = "alpine/edge"
}
alias {
name        = "alpine"
description = "Alpine Linux"
}
alias {
name        = "alpine-edge"
description = "Alpine Linux Edge"
}
}
```

Implement incus image alias nested block

---

CONTRIBUTING.md

As discussed in https://github.com/lxc/terraform-provider-incus/pull/273#issuecomment-3155398949, we will follow the Incus project to also disallow code generated by AI tooling.

Update contributing guidelines to disallow LLMs contributions

---

docs/data-sources/cluster.md
internal/acctest/checks.go
internal/clustering/datasource_cluster.go
internal/clustering/datasource_cluster_test.go
internal/provider/provider.go

Replaces #279 and #284.
Example (mainly useful for a clustered Incus setup):
```hcl
terraform {
required_providers {
incus = {
source = "lxc/incus"
}
}
}
provider "incus" {}
data "incus_cluster" "this" {
remote = "cluster"
lifecycle {
postcondition {
condition     = alltrue(self.is_clustered ? [for i, v in self.members : v.status == "Online"] : [])
error_message = "All servers must be online."
}
}
}
```
Resolves: #268

Cluster data source
